// <auto-generated />
using INF11207_TP4_Jeu_de_Pokemons_avec_EF_et_APIs_REST;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace INF11207_TP4_Jeu_de_Pokemons_avec_EF_et_APIs_REST.Migrations
{
    [DbContext(typeof(JeuDePokemonsDbContext))]
    partial class JeuDePokemonsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("INF11207_TP4_Jeu_de_Pokemons_avec_EF_et_APIs_REST.Models.EfficaciteAttaque", b =>
                {
                    b.Property<int>("EfficaciteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defend")
                        .HasColumnType("int");

                    b.Property<double>("Effectiveness")
                        .HasColumnType("float");

                    b.HasKey("EfficaciteId");

                    b.ToTable("Efficacites");

                    b.HasData(
                        new
                        {
                            EfficaciteId = 1,
                            Attack = 0,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 2,
                            Attack = 0,
                            Defend = 1,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 3,
                            Attack = 0,
                            Defend = 2,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 4,
                            Attack = 0,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 5,
                            Attack = 0,
                            Defend = 4,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 6,
                            Attack = 0,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 7,
                            Attack = 0,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 8,
                            Attack = 0,
                            Defend = 7,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 9,
                            Attack = 0,
                            Defend = 8,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 10,
                            Attack = 0,
                            Defend = 10,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 11,
                            Attack = 0,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 12,
                            Attack = 0,
                            Defend = 12,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 13,
                            Attack = 0,
                            Defend = 13,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 14,
                            Attack = 0,
                            Defend = 15,
                            Effectiveness = 0.0
                        },
                        new
                        {
                            EfficaciteId = 15,
                            Attack = 0,
                            Defend = 16,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 16,
                            Attack = 1,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 17,
                            Attack = 1,
                            Defend = 1,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 18,
                            Attack = 1,
                            Defend = 2,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 19,
                            Attack = 1,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 20,
                            Attack = 1,
                            Defend = 4,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 21,
                            Attack = 1,
                            Defend = 5,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 22,
                            Attack = 1,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 23,
                            Attack = 1,
                            Defend = 7,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 24,
                            Attack = 1,
                            Defend = 8,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 25,
                            Attack = 1,
                            Defend = 10,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 26,
                            Attack = 1,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 27,
                            Attack = 1,
                            Defend = 12,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 28,
                            Attack = 1,
                            Defend = 13,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 29,
                            Attack = 1,
                            Defend = 15,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 30,
                            Attack = 1,
                            Defend = 16,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 31,
                            Attack = 2,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 32,
                            Attack = 2,
                            Defend = 1,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 33,
                            Attack = 2,
                            Defend = 2,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 34,
                            Attack = 2,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 35,
                            Attack = 2,
                            Defend = 4,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 36,
                            Attack = 2,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 37,
                            Attack = 2,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 38,
                            Attack = 2,
                            Defend = 7,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 39,
                            Attack = 2,
                            Defend = 8,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 40,
                            Attack = 2,
                            Defend = 10,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 41,
                            Attack = 2,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 42,
                            Attack = 2,
                            Defend = 12,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 43,
                            Attack = 2,
                            Defend = 13,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 44,
                            Attack = 2,
                            Defend = 15,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 45,
                            Attack = 2,
                            Defend = 16,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 46,
                            Attack = 3,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 47,
                            Attack = 3,
                            Defend = 1,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 48,
                            Attack = 3,
                            Defend = 2,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 49,
                            Attack = 3,
                            Defend = 3,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 50,
                            Attack = 3,
                            Defend = 4,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 51,
                            Attack = 3,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 52,
                            Attack = 3,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 53,
                            Attack = 3,
                            Defend = 7,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 54,
                            Attack = 3,
                            Defend = 8,
                            Effectiveness = 0.0
                        },
                        new
                        {
                            EfficaciteId = 55,
                            Attack = 3,
                            Defend = 10,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 56,
                            Attack = 3,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 57,
                            Attack = 3,
                            Defend = 12,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 58,
                            Attack = 3,
                            Defend = 13,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 59,
                            Attack = 3,
                            Defend = 15,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 60,
                            Attack = 3,
                            Defend = 16,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 61,
                            Attack = 4,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 62,
                            Attack = 4,
                            Defend = 1,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 63,
                            Attack = 4,
                            Defend = 2,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 64,
                            Attack = 4,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 65,
                            Attack = 4,
                            Defend = 4,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 66,
                            Attack = 4,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 67,
                            Attack = 4,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 68,
                            Attack = 4,
                            Defend = 7,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 69,
                            Attack = 4,
                            Defend = 8,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 70,
                            Attack = 4,
                            Defend = 10,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 71,
                            Attack = 4,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 72,
                            Attack = 4,
                            Defend = 12,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 73,
                            Attack = 4,
                            Defend = 13,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 74,
                            Attack = 4,
                            Defend = 15,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 75,
                            Attack = 4,
                            Defend = 16,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 76,
                            Attack = 5,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 77,
                            Attack = 5,
                            Defend = 1,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 78,
                            Attack = 5,
                            Defend = 2,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 79,
                            Attack = 5,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 80,
                            Attack = 5,
                            Defend = 4,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 81,
                            Attack = 5,
                            Defend = 5,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 82,
                            Attack = 5,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 83,
                            Attack = 5,
                            Defend = 7,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 84,
                            Attack = 5,
                            Defend = 8,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 85,
                            Attack = 5,
                            Defend = 10,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 86,
                            Attack = 5,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 87,
                            Attack = 5,
                            Defend = 12,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 88,
                            Attack = 5,
                            Defend = 13,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 89,
                            Attack = 5,
                            Defend = 15,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 90,
                            Attack = 5,
                            Defend = 16,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 91,
                            Attack = 6,
                            Defend = 0,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 92,
                            Attack = 6,
                            Defend = 1,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 93,
                            Attack = 6,
                            Defend = 2,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 94,
                            Attack = 6,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 95,
                            Attack = 6,
                            Defend = 4,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 96,
                            Attack = 6,
                            Defend = 5,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 97,
                            Attack = 6,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 98,
                            Attack = 6,
                            Defend = 7,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 99,
                            Attack = 6,
                            Defend = 8,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 100,
                            Attack = 6,
                            Defend = 10,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 101,
                            Attack = 6,
                            Defend = 11,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 102,
                            Attack = 6,
                            Defend = 12,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 103,
                            Attack = 6,
                            Defend = 13,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 104,
                            Attack = 6,
                            Defend = 15,
                            Effectiveness = 0.0
                        },
                        new
                        {
                            EfficaciteId = 105,
                            Attack = 6,
                            Defend = 16,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 106,
                            Attack = 7,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 107,
                            Attack = 7,
                            Defend = 1,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 108,
                            Attack = 7,
                            Defend = 2,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 109,
                            Attack = 7,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 110,
                            Attack = 7,
                            Defend = 4,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 111,
                            Attack = 7,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 112,
                            Attack = 7,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 113,
                            Attack = 7,
                            Defend = 7,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 114,
                            Attack = 7,
                            Defend = 8,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 115,
                            Attack = 7,
                            Defend = 10,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 116,
                            Attack = 7,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 117,
                            Attack = 7,
                            Defend = 12,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 118,
                            Attack = 7,
                            Defend = 13,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 119,
                            Attack = 7,
                            Defend = 15,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 120,
                            Attack = 7,
                            Defend = 16,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 121,
                            Attack = 8,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 122,
                            Attack = 8,
                            Defend = 1,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 123,
                            Attack = 8,
                            Defend = 2,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 124,
                            Attack = 8,
                            Defend = 3,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 125,
                            Attack = 8,
                            Defend = 4,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 126,
                            Attack = 8,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 127,
                            Attack = 8,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 128,
                            Attack = 8,
                            Defend = 7,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 129,
                            Attack = 8,
                            Defend = 8,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 130,
                            Attack = 8,
                            Defend = 10,
                            Effectiveness = 0.0
                        },
                        new
                        {
                            EfficaciteId = 131,
                            Attack = 8,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 132,
                            Attack = 8,
                            Defend = 12,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 133,
                            Attack = 8,
                            Defend = 13,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 134,
                            Attack = 8,
                            Defend = 15,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 135,
                            Attack = 8,
                            Defend = 16,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 136,
                            Attack = 10,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 137,
                            Attack = 10,
                            Defend = 1,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 138,
                            Attack = 10,
                            Defend = 2,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 139,
                            Attack = 10,
                            Defend = 3,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 140,
                            Attack = 10,
                            Defend = 4,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 141,
                            Attack = 10,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 142,
                            Attack = 10,
                            Defend = 6,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 143,
                            Attack = 10,
                            Defend = 7,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 144,
                            Attack = 10,
                            Defend = 8,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 145,
                            Attack = 10,
                            Defend = 10,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 146,
                            Attack = 10,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 147,
                            Attack = 10,
                            Defend = 12,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 148,
                            Attack = 10,
                            Defend = 13,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 149,
                            Attack = 10,
                            Defend = 15,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 150,
                            Attack = 10,
                            Defend = 16,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 151,
                            Attack = 11,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 152,
                            Attack = 11,
                            Defend = 1,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 153,
                            Attack = 11,
                            Defend = 2,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 154,
                            Attack = 11,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 155,
                            Attack = 11,
                            Defend = 4,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 156,
                            Attack = 11,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 157,
                            Attack = 11,
                            Defend = 6,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 158,
                            Attack = 11,
                            Defend = 7,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 159,
                            Attack = 11,
                            Defend = 8,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 160,
                            Attack = 11,
                            Defend = 10,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 161,
                            Attack = 11,
                            Defend = 11,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 162,
                            Attack = 11,
                            Defend = 12,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 163,
                            Attack = 11,
                            Defend = 13,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 164,
                            Attack = 11,
                            Defend = 15,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 165,
                            Attack = 11,
                            Defend = 16,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 166,
                            Attack = 12,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 167,
                            Attack = 12,
                            Defend = 1,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 168,
                            Attack = 12,
                            Defend = 2,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 169,
                            Attack = 12,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 170,
                            Attack = 12,
                            Defend = 4,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 171,
                            Attack = 12,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 172,
                            Attack = 12,
                            Defend = 6,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 173,
                            Attack = 12,
                            Defend = 7,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 174,
                            Attack = 12,
                            Defend = 8,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 175,
                            Attack = 12,
                            Defend = 10,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 176,
                            Attack = 12,
                            Defend = 11,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 177,
                            Attack = 12,
                            Defend = 12,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 178,
                            Attack = 12,
                            Defend = 13,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 179,
                            Attack = 12,
                            Defend = 15,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 180,
                            Attack = 12,
                            Defend = 16,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 181,
                            Attack = 13,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 182,
                            Attack = 13,
                            Defend = 1,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 183,
                            Attack = 13,
                            Defend = 2,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 184,
                            Attack = 13,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 185,
                            Attack = 13,
                            Defend = 4,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 186,
                            Attack = 13,
                            Defend = 5,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 187,
                            Attack = 13,
                            Defend = 6,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 188,
                            Attack = 13,
                            Defend = 7,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 189,
                            Attack = 13,
                            Defend = 8,
                            Effectiveness = 0.5
                        },
                        new
                        {
                            EfficaciteId = 190,
                            Attack = 13,
                            Defend = 10,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 191,
                            Attack = 13,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 192,
                            Attack = 13,
                            Defend = 12,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 193,
                            Attack = 13,
                            Defend = 13,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 194,
                            Attack = 13,
                            Defend = 15,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 195,
                            Attack = 13,
                            Defend = 16,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 196,
                            Attack = 15,
                            Defend = 0,
                            Effectiveness = 0.0
                        },
                        new
                        {
                            EfficaciteId = 197,
                            Attack = 15,
                            Defend = 1,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 198,
                            Attack = 15,
                            Defend = 2,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 199,
                            Attack = 15,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 200,
                            Attack = 15,
                            Defend = 4,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 201,
                            Attack = 15,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 202,
                            Attack = 15,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 203,
                            Attack = 15,
                            Defend = 7,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 204,
                            Attack = 15,
                            Defend = 8,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 205,
                            Attack = 15,
                            Defend = 10,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 206,
                            Attack = 15,
                            Defend = 11,
                            Effectiveness = 0.0
                        },
                        new
                        {
                            EfficaciteId = 207,
                            Attack = 15,
                            Defend = 12,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 208,
                            Attack = 15,
                            Defend = 13,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 209,
                            Attack = 15,
                            Defend = 15,
                            Effectiveness = 2.0
                        },
                        new
                        {
                            EfficaciteId = 210,
                            Attack = 15,
                            Defend = 16,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 211,
                            Attack = 16,
                            Defend = 0,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 212,
                            Attack = 16,
                            Defend = 1,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 213,
                            Attack = 16,
                            Defend = 2,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 214,
                            Attack = 16,
                            Defend = 3,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 215,
                            Attack = 16,
                            Defend = 4,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 216,
                            Attack = 16,
                            Defend = 5,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 217,
                            Attack = 16,
                            Defend = 6,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 218,
                            Attack = 16,
                            Defend = 7,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 219,
                            Attack = 16,
                            Defend = 8,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 220,
                            Attack = 16,
                            Defend = 10,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 221,
                            Attack = 16,
                            Defend = 11,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 222,
                            Attack = 16,
                            Defend = 12,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 223,
                            Attack = 16,
                            Defend = 13,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 224,
                            Attack = 16,
                            Defend = 15,
                            Effectiveness = 1.0
                        },
                        new
                        {
                            EfficaciteId = 225,
                            Attack = 16,
                            Defend = 16,
                            Effectiveness = 2.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
